repos:
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args: [--line-length=100]
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: local
    hooks:
      - id: repro-manifest-stale
        name: repro manifest staleness guard
        entry: python scripts/hooks/check_manifest_stale.py
        language: system
        pass_filenames: false
      - id: repro-seeds-present
        name: repro seeds presence
        entry: python scripts/hooks/check_seeds_present.py
        language: system
        pass_filenames: false
